fix failure to start with emacs/lsp-mode (#507)
initializationOptions was null (it's optional but the vscode client
always sets it), which resulted in this traceback:

TypeError: Cannot read property 'svelte' of undefined
+    at LSConfigManager.update (.../dist/src/ls-config.js:61:46)
+    at PluginHost.updateConfig (.../PluginHost.js:29:21)
...snip...

Fixes regression from #411